# permissions for end users to view identities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jumpstarter-router
  name: client-viewer-role
rules:
- apiGroups:
  - jumpstarter.dev
  resources:
  - clients 
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jumpstarter.dev
  resources:
  - identities/status
  verbs:
  - get
