# permissions for end users to edit exporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jumpstarter-router
  name: exporter-editor-role
rules:
- apiGroups:
  - jumpstarter.dev
  resources:
  - exporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jumpstarter.dev
  resources:
  - exporters/status
  verbs:
  - get
