# permissions for end users to view exporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jumpstarter-router
  name: exporter-viewer-role
rules:
- apiGroups:
  - jumpstarter.dev
  resources:
  - exporters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jumpstarter.dev
  resources:
  - exporters/status
  verbs:
  - get
