apiVersion: meta.jumpstarter.dev/v1alpha1
kind: JumpstarterInstance
metadata:
  name: jump-centos
spec:
  kube-context: "centos-sig" # The kubeconfig context to talk with this jumpstarter controller
  kubeconfig: "$( var.kubeconfig )"
  endpoints:
    - "grpc.jump1.some.centos-sig.com"
  namespace: "jumpstarter-lab"
