kind: ExporterAccessPolicy
apiVersion: jumpstarter.dev/v1alpha1
metadata:
  name: ci-exporter-access
spec:
  exporterSelector:
    matchLabels:
      dut-purpose: ci
      stage: production
  policies:
    - priority: 20
      from:                 # administrators have the highest priority
      - clientSelector:
          matchLabels:
            user-type: administrator
    - priority: 10
      maximumDuration: 12h
      from:               # CI comes next, maximum 12h
      - clientSelector:
          matchLabels:
            user-type: ci
    - priority: 5          # Developers come next, can take leases for up to 2 days, but can be dynamically de-allocated by higher priority clients (spot instance)
      spotAccess: true
      maximumDuration: 48h
      from:
      - clientSelector:
          matchLabels:
            user-type: developer

