apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: jumpstarter-get-lease
spec:
  params:
    - default: 'default'
      description: The client intending to acquire the lease.
      name: client-name
      type: string
    - description: A list of label exporters in the format key=value.
      name: exporter-labels
      type: array
    - default: '3600'
      description: Maximum wait time (in seconds) for lease acquisition before timeout.
      name: timeout
      type: string
    - default: '02:00:00'
      description: Maximum time (in HH:MM:SS format) for holding lease before relasing it.
      name: lease-duration
      type: string
    - name: 'client-config'
      description: Jumpstarter client config contents, can be used instead of the workspace.
      type: string
      default: ''
  results:
    - description: The Lease ID from Jumpstarter
      name: jmp-lease-id
      type: string
  steps:
    - computeResources: {}
      image: 'quay.io/jumpstarter-dev/jumpstarter:latest'
      name: acquire-lease
      args: ["$(params.exporter-labels[*])"]
      script: |
        #!/usr/bin/env bash
         set -eux

         # If the client-config parameter is provided, create and use a new client config.
         if [ -n "$(params.client-config)" ]; then
          set +x

          CONFIG_DIR="/root/.config/jumpstarter/clients"
          CONFIG_FILE="$CONFIG_DIR/default.yaml"
          POD_TOKEN_FILE="/var/run/secrets/kubernetes.io/serviceaccount/token"
          CONFIG_CONTENT="$(params.client-config)"

          # Create the config directory if it doesn't exist and write the config content to a file
          mkdir -p "$CONFIG_DIR"
          echo "$CONFIG_CONTENT" > "$CONFIG_FILE"

          # Replace the __POD_TOKEN__ placeholder with the actual pod token
          POD_TOKEN=$(cat "$POD_TOKEN_FILE")
          sed -i "s/__POD_TOKEN__/$POD_TOKEN/g" "$CONFIG_FILE"
          
          set -x
         fi

         # Use the client name provided in the parameter
         echo "Using the client $(params.client-name)"
         jmp config client use $(params.client-name)

         # Loop through each label provided as argument and build 
         #TODO: Once the lease timeout is implemented, add the $parameter.lease-duration to the command.
         CLIENT_LEASE_CMD="jmp create lease"
         for label in "$@"; do
           IFS='=' read -r KEY VAL <<< "$label"
           CLIENT_LEASE_CMD+=" -l $KEY=$VAL"
         done

         # Request a lease
         JMP_LEASE_ID=$(timeout "$(params.timeout)" $CLIENT_LEASE_CMD --duration "$(params.lease-duration)" -o name) 

         # Output the lease ID to the Tekton results
         echo -n "$JMP_LEASE_ID" > /tekton/results/jmp-lease-id
  workspaces:
    - description: Workspace for mounting Jumpstarter client files.
      mountPath: /root/.config/jumpstarter/clients
      name: jumpstarter-client-secret
      