
apiVersion: meta.jumpstarter.dev/v1alpha1
kind: ExporterHost
metadata:
  name: ti-jacinto-j784s4xevm-01-sidekick-01
  annotations:
    beaker-instance: "ti-jacinto-j784s4xevm-01-sidekick-01.auto.bos2.dc.example.com"
spec:
  locationRef:
    name: bos2-lab1
    rack: "311"
    tray: U2
  containerImage: "$( vars.ti-exporter-image )"
  addresses:
    - "$( name ).auto.bos2.dc.example.com"
  management:
    ssh:
      host: "$( name ).auto.bos2.dc.example.com"
      user: "admin"
  power:
    snmp:
      host: "some-pdu-hostname.auto.eng.bos2.bc.somedomain.com"
      user: "$( var.pdu_st_pro3_l1_311a_user )"
      password: "$( var.pdu_st_pro3_l1_311a_password )"
      oid: "1.3.6.1.4.1.13742.6.4.1.2.1.2.1"
      plug: 32
