
apiVersion: meta.jumpstarter.dev/v1alpha1
kind: ExporterInstance
metadata:
  name: ti-jacinto-j784s4xevm-01
spec:
  type: container
  dutLocationRef:
    name: bos2-lab1
    rack: "311"
    tray: U3
  exporterHostRef:
    name: ti-jacinto-j784s4xevm-01-sidekick-01
  jumpstarterInstanceRef:
    name: "jump1-mpp-bos"
  configTemplateRef:
    name: ti-j784s4xevm
    parameters:
      name: "$( name )"
      device_address: "$( name ).auto.bos2.dc.example.com"
      pdu_host: "some-pdu-hostname.auto.eng.bos2.bc.somedomain.com"
      pdu_user: "$( vars.pdu_st_pro3_l1_311a_user )"
      pdu_password: "$( vars.pdu_st_pro3_l1_311a_password )"
      pdu_oid: "1.3.6.1.4.1.13742.6.4.1.2.1.2.1"
      pdu_plug: "34"
      device_console: "/dev/ttyUSB0"
      location_name: "bos2-lab"
  labels: # adds or overrides the template labels which will be applied to the exporter
    some: "label"
    # disabled: "true"
  notes: |
    This is a J784S4x EVM device used for testing and development.
    It is located in the BOS2 data center, Lab1, Rack 311, Tray U3.
    The device is connected to a sidekick exporter host for management.
