apiVersion: jumpstarter.dev/v1alpha1
kind: FlashBundleManifest
metadata:
  name: rcar-s4
spec:
  manufacturer: Renesas
  link: "https://www.renesas.com/en/products/automotive-products/automotive-system-chips-socs/r-car-s4-automotive-system-chip-soc-car-servercommunication-gateway"
  # boot default configuration R-Car S4 Spider, for S4SK use "bootm 0x58000000#s4sk"
  bootcmd: "bootm 0x58000000"
  shelltype: "busybox"
  login:
    login_prompt: "login:"
    username: "root"
    prompt: "#"
  default_target: "emmc"
  targets:
    emmc: "/dev/mmcblk0"
  kernel:
    file: data/flasher-automotive.itb
    address: "0x58000000"
  dtb:
    default: spider
    address: "0x48000000"
    variants:
      spider:
        bootcmd: "bootm 0x58000000#spider"
      s4sk:
        bootcmd: "bootm 0x58000000#s4sk"
      custom:
        bootcmd: "bootm 0x58000000:kernel 0x58000000:initrd 0x48000000"
