[project]
name = "jumpstarter-driver-can"
version = "0.1.0"
description = ""
authors = [
  { name = "Miguel Angel Ajo Pelayo", email = "majopela@redhat.com" },
  { name = "Nick Cao", email = "ncao@redhat.com" },
  { name = "Kirk Brauer", email = "kbrauer@hatci.com" },
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"
dependencies = ["jumpstarter", "python-can>=4.5.0", "can-isotp>=2.0.6"]

[project.entry-points."jumpstarter.drivers"]
Can = "jumpstarter_driver_can.driver:Can"
IsoTpPython = "jumpstarter_driver_can.driver:IsoTpPython"
IsoTpSocket = "jumpstarter_driver_can.driver:IsoTpSocket"

[dependency-groups]
dev = ["pytest>=8.3.2", "pytest-cov>=5.0.0"]

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[build-system]
requires = ["hatchling", "hatch-vcs", "hatch-pin-jumpstarter"]
build-backend = "hatchling.build"

[tool.hatch.build.hooks.pin_jumpstarter]
name = "pin_jumpstarter"
