apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: jumpstarter-release-lease
spec:
  params:
    - description: The lease to be released.
      name: jmp-lease-id
      type: string
    - default: 'default'
      description: The client intending to release the lease.
      name: client-name
      type: string
    - name: 'client-config'
      description: Jumpstarter client config contents, can be used instead of the workspace.
      type: string
      default: ''
  steps:
    - computeResources: {}
      image: 'quay.io/jumpstarter-dev/jumpstarter:latest'
      name: release-lease
      script: |
        #!/bin/bash
          set -eux

         # If the client-config parameter is provided, create and use a new client config.
         if [ -n "$(params.client-config)" ]; then
          # Disable logging to avoid leaking sensitive data.
          set +x

          CONFIG_DIR="/root/.config/jumpstarter/clients"
          CONFIG_FILE="$CONFIG_DIR/default.yaml"
          POD_TOKEN_FILE="/var/run/secrets/kubernetes.io/serviceaccount/token"
          CONFIG_CONTENT="$(params.client-config)"

          # Create the config directory if it doesn't exist and write the config content to a file
          mkdir -p "$CONFIG_DIR"
          echo "$CONFIG_CONTENT" > "$CONFIG_FILE"

          # Replace the __POD_TOKEN__ placeholder with the actual pod token
          POD_TOKEN=$(cat "$POD_TOKEN_FILE")
          sed -i "s/__POD_TOKEN__/$POD_TOKEN/g" "$CONFIG_FILE"
          
          set -x
         fi

         # Set the lease ID from the pipeline parameter into the environment variable
         export JMP_LEASE_ID=$(params.jmp-lease-id)

         # Switch to the specified Jumpstarter client configuration
         jmp config client use "$(params.client-name)"
         echo "Using Jumpstarter client configuration: $(params.client-name)"

         # Release the lease associated with the provided lease ID
         echo "Releasing lease: $JMP_LEASE_ID"
         jmp delete leases "$JMP_LEASE_ID"

         # Confirm release
         echo "Lease $JMP_LEASE_ID has been successfully released."
  workspaces:
    - mountPath: /root/.config/jumpstarter/clients
      name: jumpstarter-client-secret
      