apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: shell-exporter
  namespace: default
endpoint: grpc.jumpstarter.192.168.0.203.nip.io:8082
token: "<token>"
export:
  example:
    type: jumpstarter_driver_shell.driver.Shell
    config:
      methods:
        ls: "ls"
        method2: "echo 'Hello World 2'"
        #multi line method
        method3: |
          echo 'Hello World $1'
          echo 'Hello World $2'
        env_var: "echo $ENV_VAR"

