name: Unit/Functional tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - 'release-*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run make deploy
        run: make test
