name: Web Build

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      node-version:
        required: false
        type: string
        default: "18"
      package-manager:
        required: false
        type: string
        default: "npm"
      build-command:
        required: false
        type: string
        default: "npm run compile"
      test-command:
        required: false
        type: string
        default: "npm test"
      lint-command:
        required: false
        type: string
        default: "npm run lint"
      use-container:
        required: false
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      working-directory:
        required: true
        type: string
      node-version:
        required: false
        type: string
        default: "18"
      package-manager:
        required: false
        type: string
        default: "npm"
      build-command:
        required: false
        type: string
        default: "npm run compile"
      test-command:
        required: false
        type: string
        default: "npm test"
      lint-command:
        required: false
        type: string
        default: "npm run lint"
      use-container:
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: ${{ inputs.use-container && 'ghcr.io/the78mole/jumpstarter-mono/ci-node:latest' || null }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (if not using container)
        if: ${{ !inputs.use-container }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install pnpm (if not using container)
        if: ${{ !inputs.use-container && inputs.package-manager == 'pnpm' }}
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies (npm)
        if: inputs.package-manager == 'npm'
        working-directory: ${{ inputs.working-directory }}
        run: npm ci

      - name: Install dependencies (yarn)
        if: inputs.package-manager == 'yarn'
        working-directory: ${{ inputs.working-directory }}
        run: yarn install --frozen-lockfile

      - name: Install dependencies (pnpm)
        if: inputs.package-manager == 'pnpm'
        working-directory: ${{ inputs.working-directory }}
        run: pnpm install --frozen-lockfile

      - name: Run linting
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.lint-command }}

      - name: Run tests
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.test-command }}

      - name: Build
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.build-command }}
