name: Lint Go Code

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: "1.22"
      working-directory:
        required: true
        type: string
      golangci-lint-version:
        required: false
        type: string
        default: "latest"
      use-container:
        required: false
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      go-version:
        required: false
        type: string
        default: "1.22"
      working-directory:
        required: true
        type: string
      golangci-lint-version:
        required: false
        type: string
        default: "latest"
      use-container:
        required: false
        type: boolean
        default: true

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ${{ inputs.use-container && 'ghcr.io/the78mole/jumpstarter-mono/ci-go:latest' || null }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go (if not using container)
        if: ${{ !inputs.use-container }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ inputs.golangci-lint-version }}
          working-directory: ${{ inputs.working-directory }}
          args: --timeout=5m
