name: Web Build

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      node-version:
        required: false
        type: string
        default: '18'
      package-manager:
        required: false
        type: string
        default: 'npm'
      build-command:
        required: false
        type: string
        default: 'npm run compile'
      test-command:
        required: false
        type: string
        default: 'npm test'
      lint-command:
        required: false
        type: string
        default: 'npm run lint'
  workflow_dispatch:
    inputs:
      working-directory:
        required: true
        type: string
      node-version:
        required: false
        type: string
        default: '18'
      package-manager:
        required: false
        type: string
        default: 'npm'
      build-command:
        required: false
        type: string
        default: 'npm run compile'
      test-command:
        required: false
        type: string
        default: 'npm test'
      lint-command:
        required: false
        type: string
        default: 'npm run lint'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.package-manager }}
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

      - name: Install dependencies (npm)
        if: inputs.package-manager == 'npm'
        working-directory: ${{ inputs.working-directory }}
        run: npm ci

      - name: Install dependencies (yarn)
        if: inputs.package-manager == 'yarn'
        working-directory: ${{ inputs.working-directory }}
        run: yarn install --frozen-lockfile

      - name: Install dependencies (pnpm)
        if: inputs.package-manager == 'pnpm'
        working-directory: ${{ inputs.working-directory }}
        run: pnpm install --frozen-lockfile

      - name: Run linting
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.lint-command }}

      - name: Run tests
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.test-command }}

      - name: Build
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.build-command }}