name: Python Lint

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"
      working-directory:
        required: true
        type: string
      use-container:
        required: false
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"
      working-directory:
        required: true
        type: string
      use-container:
        required: false
        type: boolean
        default: true

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ${{ inputs.use-container && 'ghcr.io/the78mole/jumpstarter-mono/ci-python:latest' || null }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python (if not using container)
        if: ${{ !inputs.use-container }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install uv (if not using container)
        if: ${{ !inputs.use-container }}
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync

      - name: Run ruff check
        working-directory: ${{ inputs.working-directory }}
        run: uv run ruff check

      - name: Run ruff format check
        working-directory: ${{ inputs.working-directory }}
        run: uv run ruff format --check
