name: Lint Go Code

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: "1.25"
        description: "Go version to use"
      working-directory:
        required: true
        type: string
        description: "Working directory for the Go project"
      golangci-lint-install-mode:
        required: false
        type: string
        default: none
        description: "golangci-lint installation mode: none, goinstall or binary"
      golangci-lint-version:
        required: false
        type: string
        default: "latest"
        description: "golangci-lint version to use"
      use-container:
        required: false
        type: boolean
        default: true
        description: "Whether to use CI container"
      container-tag:
        required: false
        type: string
        default: "latest"
        description: "Container tag to use for CI container"
  workflow_dispatch:
    inputs:
      go-version:
        required: false
        type: string
        default: "1.25"
        description: "Go version to use"
      working-directory:
        required: true
        type: string
        description: "Working directory for the Go project"
      golangci-lint-version:
        required: false
        type: string
        default: "latest"
        description: "golangci-lint version to use"
      use-container:
        required: false
        type: boolean
        default: true
        description: "Whether to use CI container"
      container-tag:
        required: false
        type: string
        default: "latest"
        description: "Container tag to use for CI container"

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ${{ inputs.use-container && format('ghcr.io/the78mole/jumpstarter-mono/ci-go:{0}', inputs.container-tag) || null }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go (if not using container)
        if: ${{ !inputs.use-container }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}

      - name: Configure Git for VCS stamping
        if: ${{ inputs.use-container }}
        run: |
          git config --global --add safe.directory "$(pwd)"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: golangci-lint
        if: ${{ !inputs.use-container }}
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ inputs.golangci-lint-version }}
          working-directory: ${{ inputs.working-directory }}
          args: --timeout=5m

      - name: golangci-lint (container)
        if: ${{ inputs.use-container }}
        working-directory: ${{ inputs.working-directory }}
        run: |
          golangci-lint --version
          golangci-lint run --timeout=5m
