name: Lint Go Code

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: "1.24"
      working-directory:
        required: true
        type: string
      golangci-lint-version:
        required: false
        type: string
        default: "latest"
  workflow_dispatch:
    inputs:
      go-version:
        required: false
        type: string
        default: "1.24"
      working-directory:
        required: true
        type: string
      golangci-lint-version:
        required: false
        type: string
        default: "latest"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ inputs.golangci-lint-version }}
          working-directory: ${{ inputs.working-directory }}
          args: --timeout=5m
