name: Build Go Application

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: "1.22"
      working-directory:
        required: true
        type: string
      binary-name:
        required: true
        type: string
      cmd-package:
        required: false
        type: string
        default: "./cmd"
      build-flags:
        required: false
        type: string
        default: ""
      test-flags:
        required: false
        type: string
        default: "-v -race"
      use-container:
        required: false
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      go-version:
        required: false
        type: string
        default: "1.22"
      working-directory:
        required: true
        type: string
      binary-name:
        required: true
        type: string
      cmd-package:
        required: false
        type: string
        default: "./cmd"
      build-flags:
        required: false
        type: string
        default: ""
      test-flags:
        required: false
        type: string
        default: "-v -race"
      use-container:
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: ${{ inputs.use-container && 'ghcr.io/the78mole/jumpstarter-mono/ci-go:latest' || null }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go (if not using container)
        if: ${{ !inputs.use-container }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}
          cache-dependency-path: ${{ inputs.working-directory }}/go.sum

      - name: Verify dependencies
        working-directory: ${{ inputs.working-directory }}
        run: go mod verify

      - name: Build
        working-directory: ${{ inputs.working-directory }}
        run: |
          go build ${{ inputs.build-flags }} -o ${{ inputs.binary-name }} ${{ inputs.cmd-package }}

      - name: Run tests
        working-directory: ${{ inputs.working-directory }}
        run: |
          if [ -f Makefile ] && grep -q "^test:" Makefile; then
            make test
          else
            go test ${{ inputs.test-flags }} ./...
          fi
